import type { Person } from "./types";

const unsplash = (id: string) =>
  `https://images.unsplash.com/${id}?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080`;

export const MOCK_PERSONS: Person[] = [
  {
    id: "1",
    name: "Мария, 28",
    companyType: "Только девушки",
    location: "Грузия · Тбилиси",
    dates: "12–20 июля",
    description: "Люблю горы и вино. Ищу лёгких на подъём попутчиков для хайкинга.",
    rating: 4.9,
    photoUrl: unsplash("photo-1564564295391-7f24f26f568b"),
  },
  {
    id: "2",
    name: "Артём, 31",
    companyType: "Смешанная",
    location: "Индонезия · Бали",
    dates: "5–19 авг",
    description: "Сёрфинг, кофейни и байки. Ищу компанию для месяца на острове.",
    rating: 4.8,
    photoUrl: unsplash("photo-1758598497192-15ffa411c3de"),
  },
  {
    id: "3",
    name: "Аня и Лёша",
    companyType: "Пара",
    location: "Россия · Алтай",
    dates: "20–28 июля",
    description: "Пара, ищем ещё двоих в трек по Чуйскому тракту с палатками.",
    rating: 5.0,
    photoUrl: unsplash("photo-1655640061626-c1b0e4f81b1f"),
  },
  {
    id: "4",
    name: "Дмитрий, 26",
    companyType: "Друзья",
    location: "Турция · Каппадокия",
    dates: "1–8 сент",
    description: "Фотограф. Хочу поймать шары на рассвете, ищу единомышленников.",
    rating: 4.7,
    photoUrl: unsplash("photo-1762191850768-91dee67f6f25"),
  },
  {
    id: "5",
    name: "София, 24",
    companyType: "Смешанная",
    location: "Португалия · Лиссабон",
    dates: "10–24 авг",
    description: "Спокойный ритм, набережные и вино. Открыта к новым знакомствам.",
    rating: 4.9,
    photoUrl: unsplash("photo-1624603225543-2ef7ffb11c8f"),
  },
  {
    id: "6",
    name: "Игорь, 35",
    companyType: "Друзья",
    location: "Россия · Роадтрип",
    dates: "15–30 июля",
    description: "Есть машина, еду по Золотому кольцу. Ищу штурмана и компанию.",
    rating: 4.6,
    photoUrl: unsplash("photo-1531860494978-9326a0388ef4"),
  },
  {
    id: "7",
    name: "Карина, 29",
    companyType: "Только девушки",
    location: "Грузия · Сванетия",
    dates: "3–12 авг",
    description: "Треккинг к ледникам и гостевые дома. Ищу активных девчонок.",
    rating: 4.8,
    photoUrl: unsplash("photo-1730037656480-cb3b74c71a4d"),
  },
  {
    id: "8",
    name: "Тимур, 30",
    companyType: "Одиночное путешествие",
    location: "Индонезия · Убуд",
    dates: "1–20 сент",
    description: "Диджитал-номад, работаю удалённо. Ищу соседа по вилле.",
    rating: 4.7,
    photoUrl: unsplash("photo-1678858893494-d487f4ed09b2"),
  },
  {
    id: "9",
    name: "Алина, 26",
    companyType: "Только девушки",
    location: "Россия · Камчатка",
    dates: "18–28 июля",
    description: "Хочу увидеть вулканы и Тихий океан. Ищу спокойных попутчиц.",
    rating: 4.9,
    photoUrl: unsplash("photo-1526510747491-58f928ec870f"),
  },
  {
    id: "10",
    name: "Артём, 30",
    companyType: "Только парни",
    location: "Вьетнам · Дананг",
    dates: "3–15 авг",
    description: "Серфинг, кофе и байки. Открыт к новым знакомствам в дороге.",
    rating: 4.7,
    photoUrl: unsplash("photo-1654155427842-a4a249bf693e"),
  },
  {
    id: "11",
    name: "Ника, 27",
    companyType: "Смешанная",
    location: "Марокко · Марракеш",
    dates: "10–20 сен",
    description: "Рынки, пустыня Сахара и много специй. Люблю живые города.",
    rating: 4.8,
    photoUrl: unsplash("photo-1630939687530-241d630735df"),
  },
  {
    id: "12",
    name: "Егор, 25",
    companyType: "Группа",
    location: "Армения · Ереван",
    dates: "22 авг – 1 сен",
    description: "Горы, коньяк и древние монастыри. Собираю компанию из 3-4 человек.",
    rating: 5.0,
    photoUrl: unsplash("photo-1758599670003-ccf2c2ade8e6"),
  },
  {
    id: "13",
    name: "Анна, 27",
    companyType: "Только девушки",
    location: "Перу · Куско",
    dates: "12–24 авг",
    description: "Иду к Мачу-Пикчу, ищу компанию для трека по тропе инков.",
    rating: 4.8,
    photoUrl: unsplash("photo-1525134479668-1bee5c7c6845"),
  },
  {
    id: "14",
    name: "Дмитрий, 31",
    companyType: "Только парни",
    location: "Исландия · Рейкьявик",
    dates: "3–14 сен",
    description: "Роуд-трип по кольцевой дороге, водопады и горячие источники.",
    rating: 4.9,
    photoUrl: unsplash("photo-1619950455147-9c450d8f988a"),
  },
  {
    id: "15",
    name: "Марина и Олег",
    companyType: "Пара",
    location: "Таиланд · Пхукет",
    dates: "20 июл – 5 авг",
    description: "Пара путешественников, любим дайвинг и уличную еду.",
    rating: 4.7,
    photoUrl: unsplash("photo-1781212029261-8d7da38b10da"),
  },
  {
    id: "16",
    name: "Катя, 24",
    companyType: "Друзья",
    location: "Черногория · Котор",
    dates: "8–18 авг",
    description: "Собираем компанию друзей для яхтинга по Адриатике.",
    rating: 4.6,
    photoUrl: unsplash("photo-1613192762322-412d46d6c21c"),
  },
];

export const POPULAR_DESTINATIONS = [
  "Грузия",
  "Бали",
  "Алтай",
  "Турция",
  "Португалия",
  "Роадтрип",
];